run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - misspell

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
